### ISSUE TITLE
MVP / 0.1.0

### ISSUE THREAD

**Issue by armanbilge** [typelevel/feral#69]
@kubukoz lit the fire today to try and get a MVP out and @bpholt recently expressed similar sentiment in https://github.com/typelevel/feral/pull/60#discussion_r761426262. We have lots of good stuff here, and people seem interested :)

### TODO
- [x] https://github.com/typelevel/feral/issues/36
- [ ] https://github.com/typelevel/feral/issues/38
- [x] https://github.com/typelevel/feral/pull/60 (my preference) or https://github.com/typelevel/feral/pull/51 ?
- [x] #52, #54, #55
- [x] Models for a few events, can someone tell me what the important ones are?
       https://github.com/typelevel/feral/issues/48
- [x] Docs and an example or two https://github.com/typelevel/feral/pull/88 https://github.com/typelevel/feral/pull/93

Based on the feedback I've gotten I would love to run with https://github.com/typelevel/feral/pull/60. It's somewhat complex, but very composable IMO, and we can offer lambdas with pre-baked stacks for users who want something simpler.

**Comment by armanbilge** [comment]
Thanks all for the spree this evening, that was fantastic. I think we're in pretty good shape to get a pre-release out early this week.

Remaining TODO:
- [ ] merge https://github.com/typelevel/feral/pull/58
- [ ] take a pass through events and clean up a bit
- [ ] demonstrate `Init` in the `IOLambda.Simple` example
- [ ] create example for `IOLambda` combining resources, tracing, and http4s-middleware

There's also the issue of the following PRs which have not yet been released. None of them are critical of course, but assuming people actually want to try some of this stuff on Node.js they would certainly help :) For example, I think rn there is no `EntryPoint` implementation for JS at all, not even no-op! 🙃 
- https://github.com/tpolecat/natchez/pull/443
- https://github.com/tpolecat/natchez/pull/427
- https://github.com/tpolecat/natchez/pull/452
- https://github.com/tpolecat/natchez-http4s/pull/21
- https://github.com/tpolecat/skunk/pull/587

**Comment by armanbilge** [comment]
Oh, also I have minimal experience actually deploying these things. I did it once in an [early http4s.js experiment.](https://github.com/christopherdavenport/js-test/tree/serverless). So @kubukoz if you have bandwidth to write a small something that gives some clue how to do this that would be phenomenal.

**Comment by armanbilge** [comment]
I think we're ready to release feral 0.1.0-M1 tomorrow :) We just really need the latest natchez and natchez-http4s with Scala.js artifacts and the AWS X-Ray integration. @tpolecat, pretty please? 🥺

**Comment by armanbilge** [comment]
Draft release notes in https://github.com/typelevel/feral/releases/tag/untagged-0cd858ab4d8b7ae37b78.

**Comment by kubukoz** [comment]
I can't see it 😅 think only maintainers can see draft releases

**Comment by armanbilge** [comment]
https://github.com/typelevel/feral/releases/tag/v0.1.0-M1
